export const data = [
    {Name: 'Ambition', Description: 'You strive to keep up with and outpace the competition.', DomainSpell: 'Blind ambition', AdvancedDomainSpell: 'Competitive edge'},
    {Name: 'Air', Description: 'You can control winds and the weather.', DomainSpell: 'Pushing gust', AdvancedDomainSpell: 'Disperse into air'},
    {Name: 'Cities', Description: 'You have powers over urban environments and denizens.', DomainSpell: 'Face in the crowd', AdvancedDomainSpell: 'Pulse of the city'},
    {Name: 'Confidence', Description: 'You overcome your fear and project pride.', DomainSpell: 'Veil of confidence', AdvancedDomainSpell: 'Delusional pride'},
    {Name: 'Creation', Description: 'You have divine abilities related to crafting and art.', DomainSpell: 'Splash of art', AdvancedDomainSpell: 'Artistic flourish'},
    {Name: 'Darkness', Description: 'You operate in the darkness and take away the light.', DomainSpell: 'Cloak of shadow', AdvancedDomainSpell: 'Darkened eyes'},
    {Name: 'Death', Description: 'You have the power to end lives and destroy undead.', DomainSpell: 'Death’s call', AdvancedDomainSpell: 'Eradicate undeath'},
    {Name: 'Destruction', Description: 'You are a conduit for divine devastation.', DomainSpell: 'Cry of destruction', AdvancedDomainSpell: 'Destructive aura'},
    {Name: 'Dreams', Description: 'You have the power to enter and manipulate dreams.', DomainSpell: 'Sweet dream', AdvancedDomainSpell: 'Dreamer’s call'},
    {Name: 'Earth', Description: 'You control soil and stone.', DomainSpell: 'Hurtling stone', AdvancedDomainSpell: 'Localized quake'},
    {Name: 'Family', Description: 'You aid and protect your family and community more effectively.', DomainSpell: 'Soothing words', AdvancedDomainSpell: 'Unity'},
    {Name: 'Fate', Description: 'You see and understand hidden inevitabilities.', DomainSpell: 'Read fate', AdvancedDomainSpell: 'Tempt fate'},
    {Name: 'Fire', Description: 'You control flame.', DomainSpell: 'Fire ray', AdvancedDomainSpell: 'Flame barrier'},
    {Name: 'Freedom', Description: 'You liberate yourself and others from shackles and constraints.', DomainSpell: 'Unimpeded stride', AdvancedDomainSpell: 'Word of freedom'},
    {Name: 'Healing', Description: 'Your healing magic is particularly potent.', DomainSpell: 'Healer’s blessing', AdvancedDomainSpell: 'Rebuke death'},
    {Name: 'Indulgence', Description: 'You feast mightily and can shake off the effects of overindulging.', DomainSpell: 'Overstuff', AdvancedDomainSpell: 'Take its course'},
    {Name: 'Knowledge', Description: 'You receive divine insights.', DomainSpell: 'Scholarly recollection', AdvancedDomainSpell: 'Know the enemy'},
    {Name: 'Luck', Description: 'You’re unnaturally lucky and keep out of harm’s way.', DomainSpell: 'Bit of luck', AdvancedDomainSpell: 'Lucky break'},
    {Name: 'Magic', Description: 'You perform the unexpected and inexplicable.', DomainSpell: 'Magic’s vessel', AdvancedDomainSpell: 'Mystic beacon'},
    {Name: 'Might', Description: 'Your physical power is bolstered by divine strength.', DomainSpell: 'Athletic rush', AdvancedDomainSpell: 'Enduring might'},
    {Name: 'Moon', Description: 'You command powers associated with the moon.', DomainSpell: 'Moonbeam', AdvancedDomainSpell: 'Touch of the moon'},
    {Name: 'Nature', Description: 'You hold power over animals and plants.', DomainSpell: 'Vibrant thorns', AdvancedDomainSpell: 'Nature’s bounty'},
    {Name: 'Nightmares', Description: 'You fill minds with horror and dread.', DomainSpell: 'Waking nightmare', AdvancedDomainSpell: 'Shared nightmare'},
    {Name: 'Pain', Description: 'You punish those who displease you with the sharp sting of pain.', DomainSpell: 'Savor the sting', AdvancedDomainSpell: 'Retributive pain'},
    {Name: 'Passion', Description: 'You evoke passion, whether as love or lust.', DomainSpell: 'Charming touch', AdvancedDomainSpell: 'Captivating adoration'},
    {Name: 'Perfection', Description: 'You strive to perfect your mind, body, and spirit.', DomainSpell: 'Perfected mind', AdvancedDomainSpell: 'Perfected form'},
    {Name: 'Protection', Description: 'You ward yourself and others.', DomainSpell: 'Protector’s sacrifice', AdvancedDomainSpell: 'Protector’s sphere'},
    {Name: 'Secrecy', Description: 'You protect secrets and keep them hidden.', DomainSpell: 'Forced quiet', AdvancedDomainSpell: 'Safeguard secret'},
    {Name: 'Sun', Description: 'You harness the power of the sun and other light sources, and punish undead.', DomainSpell: 'Dazzling flash', AdvancedDomainSpell: 'Positive luminance'},
    {Name: 'Travel', Description: 'You have power over movement and journeys.', DomainSpell: 'Agile feet', AdvancedDomainSpell: 'Traveler’s transit'},
    {Name: 'Trickery', Description: 'You deceive others and cause mischief.', DomainSpell: 'Sudden shift', AdvancedDomainSpell: 'Trickster’s twin'},
    {Name: 'Truth', Description: 'You pierce lies and discover the truth.', DomainSpell: 'Word of truth', AdvancedDomainSpell: 'Glimpse the truth'},
    {Name: 'Tyranny', Description: 'You wield power to rule and enslave others.', DomainSpell: 'Touch of obedience', AdvancedDomainSpell: 'Commanding lash'},
    {Name: 'Undeath', Description: 'Your magic carries close ties to the undead.', DomainSpell: 'Touch of undeath', AdvancedDomainSpell: 'Malignant sustenance'},
    {Name: 'Water', Description: 'You control water and bodies of water.', DomainSpell: 'Tidal surge', AdvancedDomainSpell: 'Downpour'},
    {Name: 'Wealth', Description: 'You hold power over wealth, trade, and treasure.', DomainSpell: 'Appearance of wealth', AdvancedDomainSpell: 'Precious metals'},
    {Name: 'Zeal', Description: 'Your inner fire increases your combat prowess.', DomainSpell: 'Weapon surge', AdvancedDomainSpell: 'Zeal for battle'},
];
