export const data = [
    {Region: `Brevoy`, Languages: ['Varisian']},
    {Region: `Geb`, Languages: ['Osiriani']},
    {Region: `Hold of Belkzen`, Languages: ['Shoanti']},
    {Region: `Irrisen`, Languages: ['Hallit', 'Skald']},
    {Region: `Jalmeray`, Languages: ['Vudrani']},
    {Region: `Katapesh`, Languages: ['Kelish', 'Osiriani', 'Vudrani']},
    {Region: `Kelesh`, Languages: ['Kelish']},
    {Region: `Lands of the Linnorm Kings`, Languages: ['Skald', 'Tien']},
    {Region: `Mana Wastes`, Languages: ['Osiriani']},
    {Region: `Mendev`, Languages: ['Hallit']},
    {Region: `Mwangi Expanse`, Languages: ['Mwangi']},
    {Region: `Nex`, Languages: ['Osiriani', 'Vudrani']},
    {Region: `Nidal`, Languages: ['Varisian']},
    {Region: `Nirmathas`, Languages: ['Varisian']},
    {Region: `Numeria`, Languages: ['Hallit']},
    {Region: `Osirion`, Languages: ['Kelish', 'Osiriani']},
    {Region: `Qadira`, Languages: ['Kelish']},
    {Region: `Rahadoum`, Languages: ['Osiriani']},
    {Region: `Realm of the Mammoth Lords`, Languages: ['Hallit', 'Tien']},
    {Region: `Sarkoris`, Languages: ['Hallit']},
    {Region: `the Gravelands`, Languages: ['Varisian']},
    {Region: `the Shackles`, Languages: ['Mwangi']},
    {Region: `Thuvia`, Languages: ['Mwangi', 'Osiriani']},
    {Region: `Tian Xia`, Languages: ['Tien']},
    {Region: `Ustalav`, Languages: ['Hallit', 'Varisian']},
    {Region: `Varisia`, Languages: ['Shoanti', 'Varisian']},
    {Region: `Vidrian`, Languages: ['Mwangi']},
    {Region: `Vudra`, Languages: ['Vudrani']},
];
